version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: hospital_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth_service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "5101:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospitaldb

  doctor_service:
    build:
      context: ./backend/doctor-service
      dockerfile: Dockerfile
    container_name: doctor_service
    ports:
      - "5102:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospitaldb

  appointment_service:
    build:
      context: ./backend/appointment-service
      dockerfile: Dockerfile
    container_name: appointment_service
    ports:
      - "5103:5003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospitaldb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth_service
      - doctor_service
      - appointment_service
    environment:
      - AUTH_SERVICE_URL=http://auth_service:5001
      - DOCTOR_SERVICE_URL=http://doctor_service:5002
      - APPOINTMENT_SERVICE_URL=http://appointment_service:5003

volumes:
  mongo-data:
